Sprint_09
atrush/pract_01 pull request #13
Opened 2022-04-10 17:59 UTC by atrush

2022-04-10 19:42 UTC, atrush commented
* Автотест на 14 инкремент проходит через раз - иногда не укладывается в 20 сек, не знаю как поправить.

Для graceful shutdown сделал ожидание пока не завершатся асинхронные задачи.
Асинхронно работает только одна задача - удаление списка url. Проверь пожалуйста на сколько я адекватно выполнил это ожидание.

постараюсь пояснить что я пытался сделать в репозитории psql -> url :
- При добавлении списка url на удаление запускается producer DeleteURLBatch, который через канал deleteChan передает задачки на удаление в consumer initDeleteBatchWorker
- за отслеживание закрытия асинхронных задачек отвечает waitAsync, при получении ctx.Done он ждет пока отработают все producer-ы, затем закрывает deleteChan  
- по закрытию deleteChan, consumer initDeleteBatch доделывает все задачи на удаление и отправляет сигнал asyncEnded, 
- сигнал ловит psql storage с помощью runWaiterAsyncEnded и отправляет сигнал дальше в main.go

2022-04-11 19:17 UTC, Perederey requested changes
В целом PR - отличный.

А вот тест нужно поправить, там проблема в том, что это не тест не может выполниться за 20 секунд, а тест не может дождаться ответа за 20 секунд. 

Проверь, что Batch delete удаляет данные, а при обращении к удаленной ссылке в теле есть ответ и http status от сервера http.StatusGone

2022-04-11 19:17 UTC, Perederey commented on cmd/shortener/config.json
> +}
eol - надо добавить пустую строку, пользователи windows будут тебе рады

2022-04-11 19:17 UTC, Perederey commented on internal/api/server.go
> +		}
тут можно упросить

```go
if err != nil && !errors.Is(err, http.ErrServerClosed) {
    return fmt.Errorf()
}
```

в realtime сработает, так, что если ошибка == nil, то второе условие проверятся не будет

2022-04-11 19:17 UTC, Perederey commented on internal/storage/psql/storage.go
>  //  !!!! On init drop all and init tables.
тут конечно, лучше сделать маленькое cli приложение и запускать его, как бы миграции по-факту.

2022-04-11 19:17 UTC, Perederey commented on pkg/config.go
> +	cfg.tryReadFileConfig()
https://pkg.go.dev/text/template#Must - попробуй вот такой паттерн, если запускаешь такую функцию, то обязательно пытаешься считать файл. 

Конечно же, перед нужно сделать условие (а не внутри функции), что ты хочешь считать файл.

2022-04-11 19:17 UTC, Perederey commented on pkg/config.go
> +	path := getConfigPath()
тут я бы раздел бы и принимал бы просто path в переменной, тесты будет проще писать ;)

2022-04-11 19:17 UTC, Perederey commented on pkg/config.go
> +	file, err := os.OpenFile(path, os.O_RDONLY, 0777)
0777 - так не нужно, лучше 0644

0777 - это чтение, запись для всех пользователей.

2022-04-18 18:50 UTC, atrush commented on cmd/shortener/config.json
> +}
Добавил, но не очень понял, последняя строка должна заканчиваться символом переноса?

2022-04-18 18:51 UTC, atrush commented on internal/api/server.go
> +		}
поправил

2022-04-18 18:55 UTC, atrush commented on internal/storage/psql/storage.go
>  //  !!!! On init drop all and init tables.
не очень понял. т.е. вынести асинхронный функционал в отдельное cli приложение? или только кусок который следит за его выполнением. И не очень понятно как с ним взаимодействовать.

2022-04-18 21:23 UTC, atrush commented on pkg/config.go
> +	cfg.tryReadFileConfig()
сделал, только вместо паники поставил log.Fatal панику я там понимаю нельзя же бросать?

2022-04-18 21:26 UTC, atrush commented on pkg/config.go
> +	path := getConfigPath()
сделал

2022-04-18 21:35 UTC, atrush commented
еще вопрос, goland выдает предупреждение что надо обработать ошибку в defer file.Close() в функции parseFromFile, стоит ли то делать или просто игнорировать?

2022-04-18 21:37 UTC, atrush commented on internal/api/server.go
> +		}
поправил

2022-04-21 06:49 UTC, Perederey commented on cmd/shortener/config.json
> +}
ага, все верно -добавить одну пустую строку

2022-04-21 06:50 UTC, Perederey commented
> Ошибку в удалении списка вроде выловил.
> Еще вопрос, goland выдает предупреждение что надо обработать ошибку в defer file.Close() в функции parseFromFile, стоит ли это делать или просто игнорировать?

Именно в твоем случае можно игнорить, так как ты читаешь файл один раз, но если будешь на постоянной основе делать, то лучше добавить проверку.

2022-04-21 06:53 UTC, Perederey requested changes
По PR вопросов нет, но чтобы принять PR тесты должны быть зелеными, а сейчас я вижу у тебя ошибку, что сервер у тебя не может стартануть, поправь пожалуйста.

2022-04-21 06:53 UTC, Perederey commented on internal/storage/psql/storage.go
>  //  !!!! On init drop all and init tables.
да, совершенно верно - в отдельное cli приложение, а взаимодействовать можно, например в тестах вызывать его перед тем, как запускать тесты, но опять же это больше пожелание, на продакшине именно так делают обычно

2022-04-21 06:53 UTC, Perederey commented on pkg/sslcert.go
> +func genCertX509Files() error {
👍

2022-04-21 06:55 UTC, Perederey approved these changes
Все супер, теперь! Отлично! 👍

2022-04-25 23:41 UTC, merged