Increment03
atrush/pract_01 pull request #4
Opened 2022-01-10 03:38 UTC by atrush

2022-01-10 18:56 UTC, iTiky requested changes
Есть существенные недочены, которые нужно поправить.
Ещё момент на будущее: нужно создавать один PR со всеми инкрементами спринта, т.к. отсматривать отдельно инкременты неудобно как мне, так потом фиксить и ребейзить тебе =)

2022-01-10 18:56 UTC, iTiky commented on internal/storage/interface.go
> +package storage
Файл назван `interface.go`, ожидается, что тут будет интерфейс без реализации.
Лучше реализацию положить в отдельный пакет:
```go
/storage
  interface.go
  /inmemory
    storage.go
```

2022-01-10 18:56 UTC, iTiky commented on internal/storage/interface.go
> +type URLStorage struct {
У нас есть интерфейс `URLStorer` и его реализации (пока только одна), это оборачивание не добавляет пользы (но может я что-то не понимаю).

2022-01-10 18:56 UTC, iTiky commented on internal/storage/mapstore.go
> +var _ URLStorer = (*MapStorage)(nil)
👍

2022-01-10 18:56 UTC, iTiky commented on internal/storage/mapstore.go
> +	urlMap map[string]string
`map` в Go не потокобезопасна. Если прилетит два запроса в параллель, будет паника. Чтение - безопасно, но рассчитывать на это не надо, т.к. если 1-ый будет читать, а 2-ой писать - ПАНИКА 💥
Тут нужна синхронизация.

2022-01-10 18:56 UTC, iTiky commented on internal/storage/mapstore.go
> +		urlMap: initURLMap,
`urlMap: initURLMap` -> `urlMap: make(map[string]string)`
Промежуточная переменная тут не добавляет читабельности.

2022-01-10 18:56 UTC, iTiky commented on internal/storage/mapstore.go
> +func (mp *MapStorage) GetURL(shortURL string) (string, error) {
Придирка: shortURL -> shortID или просто id. shortURL - это адрес сервера + id, а сюда именно id передают.

2022-01-10 18:56 UTC, iTiky commented on internal/storage/mapstore.go
> +	longURL, ok := mp.urlMap[shortURL]
ИМХО. Лучше отделять смысловые группы кода новой строкой (и перед return, чтобы были видны точки выхода из функции). Читабельность очень ценится в индустрии.

2022-01-10 18:56 UTC, iTiky commented on internal/storage/mapstore.go
> +func (mp *MapStorage) SaveURL(srcURL string) (string, error) {
Тут смешивается бизнес-логика и функционал БД. Storage должен быть "что сказали, то и сделал", если ты понимаешь о чём я.
В данном случае лучше передать сюда ID и объект для сохранения, генерация ID не задача storage.
Ещё лучше объявить модель, где сразу будут все необходимые для работы storage поля.
Ещё раз, задача БД - положить, дать, заменить, очень грубо говоря.

2022-01-10 18:56 UTC, iTiky commented on internal/storage/mapstore.go
> +func (mp *MapStorage) SaveURL(srcURL string) (string, error) {
Я бы добавил в `/service` именно логику приложения. Сейчас тут (service) помимо генерации ID ничего и не будет, но это скоро изменится. А вот когда появятся другие имплементации БД, будет много работы для миграции логики приложения между имплементациями.

2022-01-10 18:56 UTC, iTiky commented on internal/handlers/handler.go
> +	DB storage.URLStorer
1. DB не должен быть публичным полем. Это - зависимость слоя и только он с ней должен работать (сейчас другие слои или клиенты могут выполнять операции над базой).
2. Нет конструктора для объекта. Знаю, это код который лень писать, но это признак хорошего тона в Го.

2022-01-10 18:56 UTC, iTiky commented on internal/handlers/handler.go
> +func trimFirstRune(s string) string {
Расположение функций в файле Го:
1. Тип
2. Опции для создания типа (функциональные аргументы)
3. Конструктор типа
4. Публичные методы
5. Приватные методы
6. Другие вспомогательные функции

Программисты смотрят код сверху вниз и если там располагать код, это поможет быстрее ответить на вопросы: "что это", "как создать", "как применить".

2022-01-10 18:56 UTC, iTiky commented on internal/handlers/handler.go
> +	shortURL, err := h.DB.SaveURL(string(longURL))
Перед этой строкой должен быть `defer r.Body.Close()`. Без этого будет утечка ресурсов (TCP-коннект не будет закрыт и вскоре OS будет выдавать ошибки, типа "у меня закончились файловые дескрипторы").

2022-01-10 18:56 UTC, iTiky commented on internal/handlers/handler.go
> +	fmt.Fprint(w, "http://localhost:8080/"+shortURL)
Да, но лучше и короче будет `w.Write()` (а ещё каноничней 😁)

2022-01-10 18:56 UTC, iTiky commented on internal/handlers/handler.go
> +func (h *Handler) badRequestError(w http.ResponseWriter) {
Я бы лучше принимал в эту функцию ошибку и выдавал её пользователю. Чтобы он хоть как-то мог понять, что сделал не так. Сейчас это сообщение малоинформативно.

2022-01-10 18:56 UTC, iTiky commented on internal/handlers/handler.go
> +func (h *Handler) BadRequestHandler(w http.ResponseWriter, r *http.Request) {
Не вижу применений этой функции. Роутер сам поругается на неверный ендпоинт или метод.

2022-01-10 18:56 UTC, iTiky commented on internal/handlers/handler.go
> +	http.Error(w, http.StatusText(http.StatusNotFound), http.StatusNotFound)
В качестве шутки. 404!!!! Для тупых, повторяю это текстом =)

2022-01-10 18:56 UTC, iTiky commented on cmd/shortener/main.go
> +	r := chi.NewRouter()
Роутер и сервер - это часть слоя API, т.е. `main` не нужно знать какой конкретно сервер поднимается и какой роутер использует. Задача main - инициализация зависимостей, передача их другим слоям, запуск раннеров и управление ходом выполнения.
О чем это я:
```go
// Создаём подключение к БД
db := storage.NewStorage()

// Создаём слой бизнес-логики.
// Сервис принимает не конкретную реализацию `storage.URLStorer`, а интерфейс.
// В таком случае ему могут передать nil, а ошибка конструктора нам об этом скажет.
svc, err := service.NewShortener(db) 
if err != nil {
    log.Fatal(err)
}

srv, err := api.NewServer(svc)
if err != nil {}

srv.Run()
```

Инициализировали все слои и явно что-то запустили.

2022-01-10 18:56 UTC, iTiky commented on cmd/shortener/main.go
> +	log.Fatal(http.ListenAndServe(":8080", r))
Нету graceful shutdown сервера, т.е. завершения сервера по SIGINT сигналу. Тут может два варианта (коротко, ибо это гуглится в Яндексе за 5 сек):
1. `srv.Close` при получении сигнала.
2. `srv.Start(ctx context.Context)`. Контекст можно отменить и это будет сигналом для сервера к завершению.

2022-01-13 20:46 UTC, atrush commented on internal/storage/interface.go
> +package storage
вынес обертку вокруг интерфейса в отдельный файл и переименовал в repository

2022-01-13 20:48 UTC, atrush commented on internal/storage/interface.go
> +type URLStorage struct {
я так и не понял как передать объект реализующий интерфейс в метод по ссылке. по значению работает, а по ссылке так и не нашел как сделать, в итоге в конструктор сервиса service.NewShotener передаю ссылку на объект обертку

2022-01-13 20:49 UTC, atrush commented on internal/storage/mapstore.go
> +	urlMap map[string]string
добавил mutex

2022-01-13 20:51 UTC, atrush commented on internal/storage/interface.go
> +package storage
Вынес обертку в отдельный файл, переименовал ее в repository

2022-01-13 20:57 UTC, atrush commented on internal/storage/interface.go
> +type URLStorage struct {
Проблема в том что мне надо передать ссылку на объект MapStorage в конструктор shortener.NewShortener, который принимает интерфейс  storage.URLStorer. если передаю ссылку напрямую получаю  ошибку 'undefined (type *storage.URLStorer has no field or method GetURL)' (если передаю по значению, передается нормально). В общем не разобрался, сделал обертку.

2022-01-13 20:58 UTC, atrush commented on internal/storage/mapstore.go
> +	urlMap map[string]string
добавил mutex

2022-01-13 20:58 UTC, atrush commented on internal/storage/mapstore.go
> +		urlMap: initURLMap,
убрал

2022-01-13 20:59 UTC, atrush commented on internal/handlers/handler.go
> +func (h *Handler) badRequestError(w http.ResponseWriter) {
поправил

2022-01-13 20:59 UTC, atrush commented on internal/handlers/handler.go
> +func (h *Handler) BadRequestHandler(w http.ResponseWriter, r *http.Request) {
убрал

2022-01-13 21:01 UTC, atrush commented on cmd/shortener/main.go
> +	r := chi.NewRouter()
вынес логику запуска сервера в api/Sercver, логику обработки запросов в api/handler, логику работы с ссылками ссылок в service/shortener

2022-01-13 21:01 UTC, atrush commented on cmd/shortener/main.go
> +	log.Fatal(http.ListenAndServe(":8080", r))
добавил

2022-01-13 21:04 UTC, atrush commented on internal/storage/mapstore.go
> +func (mp *MapStorage) GetURL(shortURL string) (string, error) {
при разделении логики все стало прозрачнее - почистил

2022-01-13 21:05 UTC, atrush commented on internal/storage/mapstore.go
> +	longURL, ok := mp.urlMap[shortURL]
постарался везде поправить

2022-01-13 21:05 UTC, atrush commented on internal/storage/mapstore.go
> +func (mp *MapStorage) SaveURL(srcURL string) (string, error) {
разделил логику записи в БД (mapstore) и логику работы с ссылками (shortener)

2022-01-13 21:06 UTC, atrush commented on internal/handlers/handler.go
> +	DB storage.URLStorer
поправил

2022-01-13 21:06 UTC, atrush commented on internal/handlers/handler.go
> +func trimFirstRune(s string) string {
постарался везде поправить

2022-01-13 21:06 UTC, atrush commented on internal/handlers/handler.go
> +	shortURL, err := h.DB.SaveURL(string(longURL))
поправил

2022-01-13 21:06 UTC, atrush commented on internal/handlers/handler.go
> +	fmt.Fprint(w, "http://localhost:8080/"+shortURL)
поправил

2022-01-16 20:18 UTC, iTiky requested changes
Нужны доработки.
У меня был вопрос по поводу обёртки для storage (мол, она не нужна). Я прочитал твой коммент. Он выдаёт тебе ошибку, т.к. нельзя брать указатель от интерфейса.
```go
type Stringer interface {
  String() string
}

type StringerImplementation struct {}

func (s StringerImplementation) String() { return "" }

func UseStringerDependency(s Stringer) {}

func main() {
  sByValue := StringerImplementation{}
  sByPointer := &StringerImplementation{}

  UseStringerDependency(sByValue)
  UseStringerDependency(sByPointer)
}
```
Код выше будет работать для обоих случаев. Интерфейс - это контракт, ему как бы "всё равно" что его имплементирует объект или указатель на объект. Поэтому указателей на интерфейс быть не может.

2022-01-16 20:18 UTC, iTiky commented on internal/api/handler.go
> +	svc *service.Shortener
Тут должен быть интерфейс сервиса. Это позвонил писать тесты для слоя API замокав сервис. Простое правило, любая зависимость - интерфейс (не всегда конечно, но тут справедливо).

2022-01-16 20:18 UTC, iTiky commented on internal/api/handler.go
> +	defer r.Body.Close()
Порядок должен быть такой:
1. Читаем
2. Проверяем на ошибку
3. defer Close()
Сейчас defer сработает, даже если чтение body провалилось (например его вообще нет). В этом случае будет паника, т.к. `r.Body == nil`, ну а `r.Body.Close()` тоже `nil`.
Итого, дефер только после проверки на ошибку, если была ошибка, закрывать нечего.

2022-01-16 20:18 UTC, iTiky commented on internal/api/handler.go
> +
ИМХО. В таком случае, отступ в виде пустой строки только мешает чтению кода. Я обычно придерживаюсь правила:
* перед последним return функции - всегда отступ;
* внутри чего-либо (for / if), только если перед return хотя бы два оператора;

2022-01-16 20:18 UTC, iTiky commented on internal/api/handler.go
> +	shortID := trimFirstRune(r.URL.Path)
Чтобы избежать такого чтения ID из запроса, можно изменить роутер:
```go
router.Get("/{linkID}", handler.GetURLHandler)
```
а получать переменную из роутера
```go
id := chi.URLParam(r, "linkID")
```

2022-01-16 20:18 UTC, iTiky commented on internal/api/server.go
> +func (s *Server) Shutdown(ctx context.Context) error {
Хорошо бы добавить проверку "а запущен ли сервис". В противном случае повторный вызов Shutdown может привести к панике.

2022-01-16 20:18 UTC, iTiky commented on internal/service/shortener.go
> +		var err error
Объявление переменной `err` - лишнее.
```go
shortID, err := sh.iterShortURLGenerator(...)
```

2022-01-16 20:18 UTC, iTiky commented on internal/storage/inmemory/mapstore.go
> +	mutex  *sync.Mutex
Указатель - лишний.
```go
type MapStorage struct {
  sync.Mutex

  urlMap map[string]string
}
```

2022-01-16 20:18 UTC, iTiky commented on internal/storage/inmemory/mapstore.go
> +	mu := new(sync.Mutex)
Это - лишнее. Дефолтного значения (`sync.Mutex{}`) будет достаточно.

2022-01-16 20:18 UTC, iTiky commented on internal/storage/inmemory/mapstore.go
> +	mp.mutex.Unlock()
Чаще используют `defer mp.Unlock()`, т.к. если что-то пойдет не так (паника), ресурс будет разлочен.

2022-01-16 20:18 UTC, iTiky commented on internal/storage/inmemory/mapstore.go
> +func (mp *MapStorage) GetURL(shortID string) (string, error) {
Если будет конкурентное чтение и запись из мапы, это приведет к панике. Мапу нужно защищать и на чтение. `sync.RWMutex` лучше для этого подойдет.

2022-01-17 13:26 UTC, atrush commented on internal/api/handler.go
> +	svc *service.Shortener
добавил интерфей Shortener  и соответственно переименовал сервис в  ShortURLService (он назывался Shortener)

2022-01-17 13:28 UTC, atrush commented on internal/api/handler.go
> +	defer r.Body.Close()
Понял, поправил

2022-01-17 13:34 UTC, atrush commented on internal/api/handler.go
> +	shortID := trimFirstRune(r.URL.Path)
короткая ссылка у меня кодировалась в BASE64 и лепила '/' внутрь ссылки, а это ломало подобный роут. Все поправил

2022-01-17 17:38 UTC, atrush commented on internal/api/server.go
> +func (s *Server) Shutdown(ctx context.Context) error {
как проверить вроде бы нашел - добавил, но потестировать и посмотреть работает или нет так и не сообразил как

2022-01-17 17:42 UTC, atrush commented on internal/service/shortener.go
> +		var err error
поправил

2022-01-17 17:47 UTC, atrush commented on internal/storage/inmemory/mapstore.go
> +	mu := new(sync.Mutex)
поправил

2022-01-17 17:49 UTC, atrush commented on internal/storage/inmemory/mapstore.go
> +	mp.mutex.Unlock()
понял, поправил

2022-01-17 17:52 UTC, atrush commented on internal/storage/inmemory/mapstore.go
> +func (mp *MapStorage) GetURL(shortID string) (string, error) {
понял, поправил

2022-01-17 17:59 UTC, atrush commented on internal/storage/inmemory/mapstore.go
> +	mutex  *sync.Mutex
без указателя получаю ошибку статических тестов 'range var tt copies lock: struct{name string; mp' в mapstore_test.go

2022-01-17 18:01 UTC, atrush commented on internal/storage/inmemory/mapstore.go
> +	mutex  *sync.Mutex
как обойти ошибку по другому не понимаю. так что это пока не поправил и следующее замечание тоже

2022-01-17 18:05 UTC, atrush commented on internal/storage/inmemory/mapstore.go
> +	mu := new(sync.Mutex)
поправил

2022-01-18 18:20 UTC, iTiky commented on internal/api/server.go
> +func (s *Server) Shutdown(ctx context.Context) error {
Самое простое - добавить в объект флаг `isRunning` или проверять `if httpServer != nil`

2022-01-18 18:30 UTC, iTiky commented on internal/storage/inmemory/mapstore.go
> +	mutex  *sync.Mutex
Это потому, что тест-кейсы неверно используются (`tests := []struct` у тебя). В кейсах указывают вход, ожидаемый выход, имя теста и ожидается ли ошибка (может быть ещё `PrepareMocks()`). Все зависимости создаются уже ниже (в `t.Run(tt.name, func(t *testing.T)` в твоём случае). Ты мы создаём окружение для теста, выполняем тест, сверяем выход.
У тебя в состоянии кейса указано `mp      MapStorage`, а тут должен быть указатель на объект. Ты хочешь предзаполнить БД. Обычно это делают так:
```go
type testCase struct {
  name string // имя теста
  input string // тут ShortID (твой тип 'type args struct' немного сбивает с толку)
  errExpected bool
  outputExpected string
  initFixtures func(storage *MapStorage)
}
```
Т.е. для каждого теста создаём новую БД и инициализируем её значения через `initFixtures`-функцию, которая для каждого теста запишет свои значения.

Надеюсь, ты понял что я хотел донести =)

2022-01-18 18:38 UTC, iTiky approved these changes
Хороший рефакторинг. Обрати внимание на мои ответы, я там описал почему у тебя `sync.RWMutex` без указателя не работает.

2022-01-23 17:53 UTC, merged