Sprint02
atrush/pract_01 pull request #6
Opened 2022-01-24 16:10 UTC by atrush

2022-01-25 23:15 UTC, iTiky requested changes
Нужны доработки. Пожалуйста, прочитай все мои комменты (включая 1-ый PR), есть ощущение, что некоторые ты упустил (проигнорил), посему приходится их повторять.

2022-01-25 23:15 UTC, iTiky commented on internal/api/config.go
> +type Config struct {
Не очень понятно, почему эта часть находится в `/api`, т.к. здесь конфигурация не только этого слоя. Лучше это вынести в `/pkg/config`.

2022-01-25 23:15 UTC, iTiky commented on internal/api/config.go
> +func ReadEnvConfig(cfg *Config) {
1. Лучше использовать pointer receiver для этих целей (`func (c *Config) ReadEnvConfig() error`).
2. Разделять этот код на две части можно, но их нужно вызвать внутри конструктора конфига, иначе последовательность вызовов неявна.
3. Сейчас у тебя вызывается сначала `ReadEnvConfig`, затем `ReadFlagConfig`, что неверно. Флаги позволяют настроить приложение, а env-ы - переопределить поведение "извне". Представь, что запуск приложения с флагами это Docker CMD, который задан тобой как разработчиком сервиса. А вот настроить "под себя" каждый пользователь твоего контейнера может через ENV. ENV === переопределение дефолтов + секреты.

2022-01-25 23:15 UTC, iTiky commented on internal/api/config.go
> +	_ = env.Parse(envConfig)
Нет обработки ошибок.

2022-01-25 23:15 UTC, iTiky commented on internal/api/config.go
> +	serverPort := flag.String("a", cfg.ServerPort, "порт HTTP-сервера")
1. Неявное указание default-значения. Этого стоит избегать, т.к. смотря на код оно явно не видно (дефолтны лучше задать константами в начале пакета).
2. Можно использовать `StringVar`, тогда будет чуть меньше кода.
3. Сейчас явная неразбериха с default-значениями. Я бы задал дефолты флагами (через константы), а через `caarlos0/env` переопределил их (он перетрет значения, если ENV задана).

2022-01-25 23:15 UTC, iTiky commented on internal/api/config.go
> +func NewConfig() *Config {
Я бы ещё добавил метод `Validate() error` для какой-то базовой проверки значений, иначе о неверном вводе пользователь узнает только когда приложение запущено и когда случилось какое-либо событие.

2022-01-25 23:15 UTC, iTiky commented on internal/api/handler.go
> +	if r.Method != http.MethodPost {
Ненужная проверка, т.к. в роутере для этого хендлера уже указан метод. Другой метод сюда никогда не попадет.

2022-01-25 23:15 UTC, iTiky commented on internal/api/handler.go
> +		h.badRequestError(w, "Разрешены запросы только в формате JSON!")
Скорее 415

2022-01-25 23:15 UTC, iTiky commented on internal/api/handler.go
> +		h.badRequestError(w, err.Error())
Это 500, клиент тут не виноват

2022-01-25 23:15 UTC, iTiky commented on internal/api/handler.go
> +	incoming := make(map[string]string)
Лучше задать ожидаемые и возвращаемые модели в отдельном файле:
```go
/api/model
  type ShortenRequest struct {}

  type ShortenResponse struct {}
```
Так легче читать и поддерживать код. Модели объявляют inline в редких случаях. Если тебе потребуется сгенерить Swagger-спецификацию, ты устанешь выискивать в коде все модели.

2022-01-25 23:15 UTC, iTiky commented on internal/api/handler.go
> +	jsResult, err := json.Marshal(struct {
Сорян, но это абсолютно не читабельно (см. предыдущий коммент). Модели нужно описывать отдельно.

2022-01-25 23:15 UTC, iTiky commented on internal/api/handler_test.go
> +				t.Fatal(err)
`require.NoError(t, err)`

2022-01-25 23:15 UTC, iTiky commented on internal/api/handler_test.go
> +			require.True(t, tt.outContTypeExpected == "" || res.Header.Get("Content-Type") == tt.outContTypeExpected,
Очень сложная проверка, лучше разбить на несколько.

2022-01-25 23:15 UTC, iTiky commented on internal/storage/inmemory/mapstore.go
> +	mutex  sync.RWMutex
Как я уже писал, пожалуйста, используй struct embedding.

2022-01-25 23:15 UTC, iTiky commented on internal/storage/inmemory/mapstore.go
> +		mutex:  sync.RWMutex{},
Это - лишнее, явное создание объекта не добавляет к читабельности.

2022-01-25 23:15 UTC, iTiky commented on internal/storage/infile/filestore.go
> +	cache    *map[string]string
Указатель на мапу - это лишнее. Я в первый раз вижу такое, если честно. Если не инициализировать мапу, она будет `nil`, если ты для этих целей ввел указатель.

2022-01-25 23:15 UTC, iTiky commented on internal/storage/infile/filereader.go
> +func (f *fileReader) ReadAll() (*map[string]string, error) {
Убери тут указатель на мапу и `return &data, nil` -> `return data, nil`. Смысл функции останется 1 в 1 как был.

2022-01-25 23:15 UTC, iTiky commented on internal/storage/infile/filereader.go
> +func NewFileReader(fileName string) (*fileReader, error) {
1. Объект `fileReader` - приватный, значит не должно быть конструктора, который создаёт приватный тип. Это антипаттерн в Го.
2. Если честно, то функционал этого объекта на столько мал, что выносить его отдельно я бы не стал. достаточно одного метода.

2022-01-25 23:15 UTC, iTiky commented on internal/storage/infile/filestore.go
> +	_, ok := (*f.cache)[shortID]
Здесь тоже нужен лок, т.к. это конкурентный доступ к мапе.

2022-01-25 23:15 UTC, iTiky commented on internal/storage/infile/filestore.go
> +	f.mutex.RLock()
В данном случае я бы `defer` поставил сразу после `RLock()`, а чтение из мапы ближе к проверке `ok`.

2022-01-25 23:15 UTC, iTiky commented on cmd/shortener/main.go
> +	server := api.NewServer(cfg.ServerPort, *handler)
Коммент к двум строкам ниже (не могу поставить ровно туда 😁)
Можно сильно проще:
```go
ctx, ctxCancel := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
defer ctxCancel()
```
Попробуй

2022-01-27 18:37 UTC, atrush commented on cmd/shortener/main.go
> +	server := api.NewServer(cfg.ServerPort, *handler)
нашел и попытался сделать пример с signal.NotifyContext [коммит ](https://github.com/atrush/pract_01/pull/6/commits/fd886c5c7b6e9d7b5e83dd9d85dee0796a57ad55) но начинают падать статические тесты с ошибкой 'this value of ctx is never used' пришлось вернуть старый вариант.  Я правильно понимаю что вариант с signal.NotifyContext позволяет не принимать повторные сигналы выключения?

2022-01-27 18:38 UTC, atrush commented on internal/storage/infile/filestore.go
> +	f.mutex.RLock()
поправил

2022-01-27 18:38 UTC, atrush commented on internal/storage/infile/filestore.go
> +	_, ok := (*f.cache)[shortID]
добавил

2022-01-27 18:38 UTC, atrush commented on internal/storage/infile/filereader.go
> +func NewFileReader(fileName string) (*fileReader, error) {
поправил

2022-01-27 18:38 UTC, atrush commented on internal/storage/infile/filereader.go
> +func (f *fileReader) ReadAll() (*map[string]string, error) {
убрал

2022-01-27 18:38 UTC, atrush commented on internal/api/config.go
> +func NewConfig() *Config {
добавил

2022-01-27 18:38 UTC, atrush commented on internal/api/config.go
> +	serverPort := flag.String("a", cfg.ServerPort, "порт HTTP-сервера")
ок, понял, поправил

2022-01-27 18:39 UTC, atrush commented on internal/api/config.go
> +	_ = env.Parse(envConfig)
добавил

2022-01-27 18:39 UTC, atrush commented on internal/api/config.go
> +func ReadEnvConfig(cfg *Config) {
поправил

2022-01-27 18:39 UTC, atrush commented on internal/api/config.go
> +type Config struct {
перенес

2022-01-27 18:39 UTC, atrush commented on internal/api/handler.go
> +	if r.Method != http.MethodPost {
убрал

2022-01-27 18:39 UTC, atrush commented on internal/api/handler.go
> +		h.badRequestError(w, "Разрешены запросы только в формате JSON!")
поправил

2022-01-27 18:40 UTC, atrush commented on internal/api/handler.go
> +		h.badRequestError(w, err.Error())
поправил

2022-01-27 18:40 UTC, atrush commented on internal/api/handler.go
> +	incoming := make(map[string]string)
вынес в в модель, туда же добавил валидацию, да так действительно удобнее

2022-01-27 18:40 UTC, atrush commented on internal/api/handler.go
> +	jsResult, err := json.Marshal(struct {
поправил

2022-01-27 18:40 UTC, atrush commented on internal/api/handler_test.go
> +				t.Fatal(err)
поправил

2022-01-27 18:41 UTC, atrush commented on internal/api/handler_test.go
> +			require.True(t, tt.outContTypeExpected == "" || res.Header.Get("Content-Type") == tt.outContTypeExpected,
поправил

2022-01-27 18:41 UTC, atrush commented on internal/storage/inmemory/mapstore.go
> +	mutex  sync.RWMutex
ок, только сейчас дошло что не нужно вовсе объявлять поле. поправил

2022-01-27 18:41 UTC, atrush commented on internal/storage/inmemory/mapstore.go
> +		mutex:  sync.RWMutex{},
поправил

2022-01-27 18:42 UTC, atrush commented on internal/storage/infile/filestore.go
> +	cache    *map[string]string
поправил

2022-01-27 18:46 UTC, atrush commented
Пересмотрел замечания по обеим итерациям в первом инкременте. Если есть неустраненные замечания помимо указателей на mutex в mapstore, пожалуйста проговори чтобы я не упустил. если надо, вот [ссылка](https://github.com/atrush/pract_01/pull/4 )на предыдущий pr

2022-01-27 19:35 UTC, iTiky commented on cmd/shortener/main.go
> +	server := api.NewServer(cfg.ServerPort, *handler)
Нет, этот вариант просто делает код чище. Если он ругается, что ctx объявлен, но не используется, значит в зависимости ты передаешь не ctx от `signal.NotifyContext`, а какой-то другой. С этим подходом он должен быть один на весь main (контекст).

2022-01-27 19:52 UTC, iTiky approved these changes
Отлично!
У меня есть проблема, я не вижу изменений в PR относительно твоих предыдущих коммитов (моего предыдущего ревью). Не могу понять в чём дело. Посему я мог что-то пропустить. Ты, случайно, не Force push делаешь на каждый коммит? Или баг GH...

2022-01-27 19:52 UTC, iTiky commented on internal/api/model.go
> +	validate := validator.New()
Ой, я бы не советовал привыкать к валидация через тэги, это не используется в реальных проектах. Во-первых, это рефлексия. Во-вторых, это очень базовая валидация. В-третьих, а что если нужно проверить поля в связке, т.е. в зависимости от значения одного, валидация второго - меняется.
Чаще используют такой паттерн (здесь - это лишнее, просто для справки):
```go
type MyStruct struct {}

type MyStructValidator func (m MyStruct) error

func (m MyStruct) Validate(opts ... MyStructValidator) error {
  // Тут базовая валидация

  // Тут кастомная (её может и не быть)
  for _ opt := range opts {
    if err := opt(m); err != nil {
      return err
   }
  }
}
```
Объекты могут быть сложные и на каком-то этапе нужна простая валидация, на другой нужно добавить какую-то тонкую проверку.

2022-01-29 15:35 UTC, merged